---
#
#
#   Updates all OS packages
#
#   Use cautiously!
#

- hosts: all
  gather_facts: true
  become: yes
  become_user: root

  tasks:

    - name: Upgrade all packages
      apt:
        name: '*'
        state: latest

    - name: Reboot
      reboot:
        reboot_timeout: 600
